# Generated by Django 4.1.7 on 2023-02-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cover',
            field=models.ImageField(default=True, upload_to='products/cover/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchasePrice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='salePrice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
